language: java

jdk:
  - openjdk17

sudo: false

env:
  global:
    - CODECOV_TOKEN="bb0882c2-0100-4a20-86b2-55e7e26923cf"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - eyakubovskiy@gmail.ru
    on_success: never # default: change
    on_failure: always # default: always